spring:
  h2.console: true
  path: h2
  datasource:
    url: jdbc:h2:mem:productsearch;DB_CLOSE_DELAY=-1;
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    url: ${spring.datasource.url}
    schemas: PUBLIC