application:
  name: "product-search"

server:
  servlet:
    context-path: /product-search

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /health

spring:
  h2.console: true
  path: h2
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
    type: com.zaxxer.hikari.HikariDataSource
    minIdle: 5
    maxPoolSize: 25
    idleTimeout: 30000
    maxWait: 250
    maxLifeTime: 600000
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      format_sql: true
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0
    schemas: PUBLIC

