application:
  name: "product-search"

server:
  servlet:
    context-path: /product-search

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /health

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    minIdle: 5
    maxPoolSize: 25
    idleTimeout: 30000
    maxWait: 250
    maxLifeTime: 600000
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0

